# Generated by Django 3.1.4 on 2020-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Departamento', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Sumario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='encomienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Departamento', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Sumario', models.TextField()),
                ('Recibido', models.BooleanField(default=False)),
                ('Entregado', models.BooleanField(default=False)),
            ],
        ),
    ]
