# Generated by Django 3.1.2 on 2020-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='Información',
            new_name='Sumario',
        ),
        migrations.RenameField(
            model_name='encomienda',
            old_name='Información',
            new_name='Sumario',
        ),
    ]
