# Generated by Django 3.1.4 on 2020-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0002_auto_20201226_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Departamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='Departamento',
            field=models.IntegerField(),
        ),
    ]
