# Generated by Django 3.1.2 on 2020-11-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0002_auto_20201110_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='Recibido',
            field=models.BooleanField(default=False),
        ),
    ]
