# Generated by Django 3.1.2 on 2020-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0002_auto_20201227_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Departamento',
            field=models.IntegerField(),
        ),
    ]
