# Generated by Django 3.1.2 on 2020-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0002_auto_20201229_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conserje.departamento'),
        ),
    ]
