# Generated by Django 3.1.2 on 2020-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0003_auto_20201227_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
