# Generated by Django 3.1.2 on 2020-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conserje', '0004_auto_20201229_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='Hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
