# Generated by Django 3.1.2 on 2020-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encomiendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomienda',
            old_name='Recibido',
            new_name='Entregado',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='Departamento',
            field=models.IntegerField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
