# Generated by Django 3.1.2 on 2020-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encomiendas', '0002_auto_20201101_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='Departamento',
            field=models.IntegerField(),
        ),
    ]
